# version: '3.9'

services:
  app:
    build: .
    image: ${APP_NAME}:latest
    container_name: ${APP_NAME}
    volumes:
      - ./:/var/www/html
      - /dev/null:/var/www/html/.dockerignore
      - /dev/null:/var/www/html/docker-compose.yaml
      - /dev/null:/var/www/html/Dockerfile
      - node:/var/www/html/node_modules
      - laravel:/var/www/html/vendor
    command: sh ./start.sh
    ports:
      - 8000:80
      - 5173:5173
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
  mysql:
    image: mariadb:10.11.13
    container_name: mysql_${APP_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - global:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin_${APP_NAME}
    depends_on:
      - mysql
    environment:
      UPLOAD_LIMIT: 50M
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 80:80
volumes:
  global:
    name: ${APP_NAME}_global
  node:
    name: ${APP_NAME}_node
  laravel:
    name: ${APP_NAME}_laravel
